const attributeColor = {
    'FACT-BL': '#FFBFAF',
    'FACT-HE': '#AFFFBF',
    'FACT-SO': '#BFAFFF',
    'FACT-BA': '#FFF3AF',
    'FACT-OT': '#AFF7FF',
    'FACT-LZ': '#AFD1FF',
    'FACT-SW': '#FFAFF3',
    'FACT-OR': '#FFAFD1',
    'FACT-DS': '#E3AFF7',
    'FACT-UH': '#AFFFCF',
    'FACT-DE': '#AFD1FF',
    'FACT-KR': '#CFFFAF',
    'FACT-DW': '#CFAFFF',
    'FACT-SK': '#FFFACF',
    'FACT-SY': '#FFD4B2',
    'RARI-M': '#FFBFAF',
    'RARI-L': '#AFFFBF',
    'RARI-E': '#BFAFFF',
    'RARI-R': '#FFF3AF',
    'RARI-U': '#AFF7FF',
    'RARI-C': '#AFD1FF',
    'ROLE-A': '#FFAFF3',
    'ROLE-D': '#FFAFD1',
    'ROLE-H': '#E3AFF7',
    'ROLE-S': '#AFFFCF',
    'AFFI-F': '#AFD1FF',
    'AFFI-M': '#CFFFAF',
    'AFFI-S': '#CFAFFF',
    'AFFI-V': '#FFFACF',
};

export default attributeColor;
